### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#135]
At the moment, the app is only available in English. To reach our target group here in Germany (= non-tech savvy users), we'd actually need a German version as well. Ideally, the language would be chosen based on the operating system's language: German, if the phone is set to German and English in all other cases.

- [ ] quick research: What (simple) libraries are there? Does Ionic already provide some localization mechanisms?
- [ ] implement localization to German

**Comment by thierna** [comment]
- [ ] choose if we want to "Du" or "Sie" participants in German
- [ ] test if localization works as expected

**Comment by schrooom** [comment]
I'm currently looking various solutions to this task. Promising approaches, which I'll be looking at for now, are

- [ngx-translate](https://ionicframework.com/docs/v3/developer-resources/ng2-translate/)
- [Angular i18n](https://angular.io/guide/i18n-overview)
- [Transloco](https://ngneat.github.io/transloco/)

**Comment by schrooom** [comment]
We're currently taking a deeper look at [Angular i18n](https://angular.io/guide/i18n-overview), as this is the built-in way for localization.

> @thierna: choose if we want to "Du" or "Sie" participants in German

Good point! I'd prefer "Du", because _I personally_ think "Sie" feels somewhat artificially formal for an app and might even be kind of outdated in such a context nowadays?

**Comment by schrooom** [comment]
@felixerdy and I took a deeper look at above options:

[Angular i18n](https://angular.io/guide/i18n-overview) turned out to be not really applicable for our use case, as it exclusively supports AOT-compiling. This means we cannot change the locale at runtime (which is usual for mobile apps; this seems to be primarily aiming at website).

[ngx-translate](https://ionicframework.com/docs/v3/developer-resources/ng2-translate/) and [Transloco](https://ngneat.github.io/transloco/) are pretty similar in how they work and both support runtime localization. We're going to use `ngx-translate` for now, since this is more broadly established while `transloco` is a rather young project.

**Comment by schrooom** [comment]
@felixerdy and I successfully implemented the localization-lib `ngx-translate`, which for now supports german and english - given the template files we created (`assets/i18n/de.json` and `assets/i18n/en.json`).

Of course we already translated the app from english to german, that said: the translation might not be in its final form and there for sure is room for improvement.

English is the default language for now, meaning: If the users device is set to some other language other than german or english, the app will always fallback to english. Further languages can easily be added by simply creating another translation-file using the corresponding language-code (e.g. `nl.json` for dutch).
