### ISSUE TITLE
Add imprint text

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#138]
For rolling out the app in the Google PlayStore, we'd, need an imprint text.
- [x] German
- [x] English

**Comment by schrooom** [comment]
Looking great!

I took the liberty to wrap the imprint in an `ion-grid` similar to e.g. the privacy policy – otherwise the content might reach into the safe-area on iOS-devices (= covered by the notch in landscape-orientation).

Another thought: Could the imprint (e.g. above the content) be an appropriate space to include the Simport and BMBF logos? Should they even be included in the app?

→ https://raw.githubusercontent.com/sitcomlab/simport-learning-app/develop/documents/simport_bmbf_logo.png
