### ISSUE TITLE
Monkey testing

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#151]
Time for some monkey testing! Since the app will be uses by a larger audience (20 people in study), we should make sure that there is no quirky UI behavior or instability when it is not used by expert users (= us).

Tasks:

- [x] Quick research on UI monkey testing
- [x] Once https://github.com/sitcomlab/simport-learning-app/issues/149, https://github.com/sitcomlab/simport-learning-app/issues/130 and https://github.com/sitcomlab/simport-learning-app/issues/137 are in the development branch, execute test sessions on actual Android and iOS devices
- [x] Document findings

**Comment by JuanFFranco** [comment]
- When trying to import large files (greater than 10MB) different than JSON, the app crashes and closes automatically.
- When exporting trajectory and share through WhatsApp successfully, still gets notification that `Trajectory could not be exported`.
- In `Create entry` for the diary, the date is presented in forma `dd/mm/yyyy`, but when going back to `Diary`, it changes to `mm/dd/yyyy`.
- After clicking `toggle location`, can't go back to bounding box of complete trajectory.
- If all filters are deactivated, no inferences will be shown. Could be confusing when a user forgets that has the filters activated and does not see any inferences ever, an is not easy to realized that could be because of that.

**Comment by JuanFFranco** [comment]
-Imprint and privacy policy text is black in dark mode so you can't read it
