### ISSUE TITLE
Installation notification text

### ISSUE THREAD

**Issue by thierna** [sitcomlab/simport-learning-app#160]
When you install the app, you get presented with a short text, that reads:
do you want to install this application? It does not require any special access.
(as I understand the app requires access to location tracking)

![Screenshot_20220223-144755_Package_installer](https://user-images.githubusercontent.com/7602648/155732473-36c424b7-5cf3-4894-93bf-9aada76a3a87.png)

**Comment by zven** [comment]
Look into this topic and find out where / how to provide the needed information (manifest file?).

**Comment by felixerdy** [comment]
This screen is only visible on certain devices when installing the App manually. When distributing the app via Google Play Store, this screen won't be visible as the required permissions are listed in the app details.

Android differentiates between "Normal Permissions" (like internet access) which are listed in the Play Store and granted on install time. "Dangerous Permissions" (like location access or reading file system) are requested on run time and need active consent by users.

Older versions (below Android 6) of Android requested all permissions (normal and dangerous) upfront in a screen similar to the screenshot in the issue. The screen is however gone nowadays since the permissions are requested on run time.

I just tested the behavior of installing the .apk on different devices / simulators. Android 12 & 10 both have a very simple dialog which does not state anything regarding permissions:

<img width="382" alt="Bildschirmfoto 2022-03-02 um 14 31 39" src="https://user-images.githubusercontent.com/12086004/156371921-ed6bef36-ee17-462f-a8a9-d6a1920005fa.png">

Android 9 and lower seem to use the given screen.

Since we want to distribute the app via the Play Store and there is no way to influence the given screen I think there is nothing we should worry about.

Further information can be found here https://developer.android.com/guide/topics/permissions/overview (but I did not find a official documentation regarding this special screen)
