### ISSUE TITLE
Logfile feature

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#179]
Some ideas for parameters that can be logged
- log every 15 (?) minutes
- current number of locations
- current number of staypoints
- if tracking is active (-> switch toggled in UI)
- if tracking is actively paused
- timestamp of last location update

Purpose:
- be able to analyze afterwards if tracking was even active during the study / how long it was turned off
- make sure that participant has used the app as intended during the study?

Open issues:
- How can constant logging be realized? (constant = regular intervals) if app is in background?
- Log event based? -> E.g. whenever a location comes in (e.g. when app is in background)?
- Is it sufficient if we log only when app is in foreground?

Aim of this card:
- Implement simple logging feature where a number of events is logged to a CSV: app starts, user starts tracking, tracking is paused, tracking is resumed, tracking is stopped, app enters foreground. For each of those events, we store the number of stored locations and the latest location timestamp.
- CSV logfile should be send to us together with diary/logbook file

**Comment by felixerdy** [comment]
I came up with an idea where one could set some properties in log events so that we could filter them more efficient later on. Here is a proposal of log properties:
```ts
/**
 * @description What happens in the log event?
 */
export enum LogEventType {
  start = 'start',
  stop = 'stop',
  click = 'click',
  change = 'change',
  active = 'active',
  inactive = 'inactive',
  other = 'other',
}

/**
 * @description In which scope does the log event happen?
 */
export enum LogEventScope {
  app = 'app',
  tracking = 'tracking',
  inference = 'inference',
  other = 'other',
}

/**
 * @description Log level
 */
export enum LogEventLevel {
  info = 'info',
  warn = 'warn',
  error = 'error',
}
```
And logging could look something like this (e.g. when app state changes to active):
```ts
logService.log(
  LogEventType.active,
  LogEventScope.app,
  'AppStateChange'
)
```

Some properties like `LogEventLevel` will have a default value in the log function (here: `info`)
The `log` function itself will then also store additional stuff like last location timestamp or count of locations in trajectory

Is the approach with the enums too complex? I think it can improve the filtering of the .csv file afterwards but also might be a little bit overkill

**Comment by schrooom** [comment]
Nice – looks like a very good approach to me! Doesn't look too complex either: I'd argue that it is always good to have such options for filtering, even if we're ending up not making use of them in their full capacity. :+1:
