### ISSUE TITLE
Logbook: Inconsistent formatting of date

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#182]
As @JuanFFranco has found out here https://github.com/sitcomlab/simport-learning-app/issues/151, there seems to be an inconsistency regarding the formatting of dates:

> In `Create entry` for the diary, the date is presented in forma `dd/mm/yyyy`, but when going back to Diary, it changes to `mm/dd/yyyy`.

This needs to be verified and fixed.

**Comment by JuanFFranco** [comment]
This issue depends on the language, since the function `d.toLocaleDateString(locale)` returns the date on the format in which the phone is configured. The problem still persists with ***English (UK)*** configuration. Here some screenshots on how it looks:

- German

![Screenshot_2022-04-20-05-56-28-755_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/164148400-b2b726f8-fae7-4902-aad2-aee0450f8600.jpg) ![Screenshot_2022-04-20-05-56-33-896_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/164148411-2a29f04c-aa62-4942-95af-0cd5c6d24987.jpg)

- English (UK)

![Screenshot_2022-04-20-05-57-37-240_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/164148539-a331db1f-3411-491c-8bbe-ebb89a138501.jpg) ![Screenshot_2022-04-20-05-57-47-817_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/164148594-52ab8be7-4bd2-43c6-af13-2dd6ae83ebc7.jpg)

- English (US)

![Screenshot_2022-04-20-05-58-51-329_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/164148621-c5938fb3-c21e-44dd-ac9f-cc269c98d442.jpg) ![Screenshot_2022-04-20-05-59-02-208_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/164148626-d9b0440b-f751-4af9-b1b9-2dd8dd08d24a.jpg)

**Comment by zven** [comment]
@JuanFFranco A pull request is missing for this card. ;-)

**Comment by felixerdy** [comment]
Closed in #191
