### ISSUE TITLE
Wrong duration for user generated trajectory

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#21]
![567312AF-F59F-4489-90FB-A0C4A6EE276A](https://user-images.githubusercontent.com/2930332/100064024-47a26680-2e32-11eb-8484-1ad73f7d13cd.png)

Yesterday, I freshly installed the app on an iPhone and let it run for a few hours. 51 years is suspiciously close to 1970. I guess there is an issue with computing the duration based on a first / "null" Date object.

**Comment by noerw** [comment]
- Date serialization to DB (without validation!) happens here https://github.com/sitcomlab/simport-learning-app/blob/develop/src/app/shared-services/db/sqlite.service.ts#L177
- Maybe check the DB; is the first timestamp 1970-01-01T00:00:00?

**Comment by schrooom** [comment]
The db-column _time_ for table _points_ was _DATETIME_-type, which translates to _NUMERIC_ in SQLite, while we tried to save ISO-strings for datetime there. For example we stored "2021-02-10T15:23:45", which was read as a number (the first few digits until a non-numeric char), in this case: _2021_.

For reference from [here](https://www.sqlite.org/datatype3.html):
![Bildschirmfoto 2021-02-10 um 16 27 21](https://user-images.githubusercontent.com/17469296/107532609-5d683200-6bbe-11eb-8bf1-6b36d5899788.png)

I changed the datatype for that column to _TEXT_, which works flawlessly, but it needs a reinstall of the app to regenerate the db-tables. Migration of the database is not really possible out of the box, since the data within the old tables is corrupt based on this bug + sqlite does not support modifying column-types apparently - that would need some manual work. While I am open to everything, I don't think db-migration is necessary at this point and reinstalling the app is feasible.

**Comment by zven** [comment]
@schrooom What do you think about leaving the data type in the table as _DATETIME_ but changing the serialization?

**Comment by schrooom** [comment]
> @schrooom What do you think about leaving the data type in the table as _DATETIME_ but changing the serialization?

Would work too, e.g. using timestamps. Reinstalling the app is possibly still necessary then, because the current db-content is still broken:

> For example we stored "2021-02-10T15:23:45" [as a string], which was read as a number (the first few digits until a non-numeric char), in this case: 2021.

I'll look into it.

**Comment by zven** [comment]
Resolved by https://github.com/sitcomlab/simport-learning-app/pull/35
