### ISSUE TITLE
Address issues in Google Play Console

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#217]
Even after addressing the issues that were raised here https://github.com/sitcomlab/simport-learning-app/issues/208, we still can't promote our app into a closed beta test:
![prominent_disclosure](https://user-images.githubusercontent.com/2930332/178705136-d1ea6692-dfe6-4bcb-ac43-553136e83fc3.png)

**Comment by felixerdy** [comment]
<img width="726" alt="Bildschirmfoto 2022-07-18 um 09 33 22" src="https://user-images.githubusercontent.com/12086004/179463868-6935c81e-af3b-4dde-b5b2-3727be91a35e.png">

**Comment by felixerdy** [comment]
We did the following to resolve the issues on Google Play:
- Move privacy policy of the app to a seperate area on the website (https://simport.net/learning-app-privacy-policy/) which is linked in the Google Play Console
- The location access dialog is now updated in order to fulfill Googles requirements:
    - User wants to record her/his location
    - We display informed consent with information why the location is needed 
    - We request the current location once in order to toggle the OS default location access dialog
    - Afterwards, we show another custom dialog to request users to enable background location tracking in the settings
    
 TODO: apply the changes done in the `study-1` branch to the `develop` branch
