### ISSUE TITLE
Tracking state in UI does not reflect real tracking state

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#234]
One participant in the pre-study reported that the tracking stopped after approx. one day and they only realized this after a few days. To try out what happens, the participant deactivated the tracking for half an hour and re-activated it again after the elapsed time. While observing their data, the participant realized that their trajectory was showing up for approx. 30 minutes and this period also matched the time when they had the tracking turned _off_.

This leads to the assumption that the state of the button in the UI was switched around and not properly updated.

Alternative assumption: The participant has turned the tracking off and on and afterwards the phone was recording for approx. 30 minutes.

**Comment by JuanFFranco** [comment]
There are some cases that the tracking button behaves strange:

- Some cases, trying to stop the location tracking and leaving the reminder as default, had to press the button three times before changing the status (tried to replicate and record screen several times but couldn't). (Couldn't find the behavior mentioned reflected in the log)
- When staying in the same place for a long time (for example at the office or overnight), the tracking stops automatically.
- Some cases when losing signal for a while, for example while in the U-Bahn, the tracking stopped, but not every time (probably has a time tolerance?).
- When tracking is activated and phone turns off, the tracking stops automatically (for example when battery dies and charging the phone again).
- In all cases, `autostart` in app configuration settings was disabled too. (Could it be that because for external reason, like phone turning off, the user started the tracking again but forgot to set the `autostart` on again?
- Checked the code, and it does not seem that the button is inverted.

**Comment by zven** [comment]
It seems like the reported behaviour can't be reproduced.
