### ISSUE TITLE
Rename "Toggle location" button in map view

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#240]
"Toggle location" / "Position ein- / ausblenden" does not make too much sense: The button does not show / hide the location but zooms in on it. Rename into "Zoom in" or sth. similar?

**Comment by zven** [comment]
- [x] Check if it follows the last location
- [x] and check what the button actually does at the moment
- [x] rename to "Current location"

**Comment by JuanFFranco** [comment]
The button only zooms in to the last location. 
It does not follow the current location since the map view does not update automatically.

Should name in German keep the same? ("Position ein- / ausblenden")

![Screenshot_2022-10-19-05-12-43-500_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/196588865-4367740c-8ae8-4560-9af0-9562af0f83cd.jpg)

**Comment by zven** [comment]
EN: "Zoom to last location"
DE: "Letzter Standort"

**Comment by JuanFFranco** [comment]
Result: 

![Screenshot_2022-10-26-09-39-36-028_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/197965239-e54fc4a4-1c03-44e6-be57-0ad05eb9ad67.jpg) ![Screenshot_2022-10-26-09-43-10-880_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/197965268-073b2618-3e7a-41b9-a36d-b71ab46185ef.jpg)
