### ISSUE TITLE
Add location always in use description for iOS

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#27]

**Comment by zven** [comment]
@schrooom When executing "ionic cap sync ios" or "ionic cap build ios" the app I get an error:

`[fatal] Unable to read: */simport-learning-app/ios/App/App/Info.plist` and in turn I can't execute the app with Xcode.

**Comment by zven** [comment]
Update: Error persists but deployment via Xcode works. The previously mentioned problems were related to some settings on my machine.

**Comment by zven** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-02-10 at 11 54 55](https://user-images.githubusercontent.com/2930332/107500793-e4091900-6b96-11eb-984a-a18c8b796bbd.png)

@schrooom Your recent changes seemed to have broken the actual feature.

**Comment by schrooom** [comment]
No idea what went wrong for you, but it works for me. Since you have the app installed twice, maybe this dialog roots from the wrong version? I also renamed the branch form 'ios-location-description' to 'feature/ios-location-description' - sorry, if that caused any confusion.

<img width="367" alt="Bildschirmfoto 2021-02-10 um 12 56 06" src="https://user-images.githubusercontent.com/17469296/107507128-685f9a00-6b9f-11eb-888b-c9bd39d8a0b1.png">

**Comment by zven** [comment]
Ah, I was still on the branch 'ios-location-description'.
