### ISSUE TITLE
Tweak inference and POI computation

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#321]

**Comment by jbraese** [comment]
There is two parameters in the inference service we can tweak easily if we want to show more POIs. The first one is how many staypoints (15 min within 150m) need to be logged at a certain place before a POI is created. This parameter, CLUSTERING_POINTS_IN_NEIGHBORHOOD, is currently at 3. We can decrease it to show more POIs sooner. Generally, this will also increase the faulty (due to GPS noise or inconsistent tracking) or irrelevant points shown to users. The second parameter is the maximum distance that guarantees that two staypoints are clustered together (CLUSTERING_NEIGHBORHOOD_RADIUS, currently at 15m). Note that this parameter is transitive, so two staypoints with 50m distance might still be clustered together if they are joined by two staypoints in the middle. Basically this parameter determines whether we want more small clusters or fewer large clusters. In my testing now I found that we can somewhat decrease the noise created by lower CLUSTERING_POINTS_IN_NEIGHBORHOOD through simultaneously increasing this CLUSTERING_NEIGHBORHOOD_RADIUS.
I suggest three possible configs:
a) CLUSTERING_POINTS_IN_NEIGHBORHOOD = 3, CLUSTERING_NEIGHBORHOOD_RADIUS = 15. This is the current config and is quite conservative - only important points with at least three visits are shown to users. The low radius should make it relatively precise, e.g. being able to distinguish clusters between buildings in the same street. 
b) CLUSTERING_POINTS_IN_NEIGHBORHOOD = 2, CLUSTERING_NEIGHBORHOOD_RADIUS = 30. Middle of the road - we show POIs after two visits, and sacrifice some precision in distinguishing between close POIs. 
c) CLUSTERING_POINTS_IN_NEIGHBORHOOD = 1, CLUSTERING_NEIGHBORHOOD_RADIUS = 50 (This option requires also adjusting one filter in the inference engine). The most adventurous config - every staypoint is shown as a POI, which could lead to some false positives. But it might be nicer to interact with as it shows a POI immediately after one leaves a restaurant, for example. A high clustering radius avoids too much noise, but could lead to places that are e.g. in the same block to be shown as one POI.
