### ISSUE TITLE
UI: Trajectory visualization

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#76]
When there are a lot of points in one area, those clusters do basically look as if somebody has scribbled across the map with a thick crayon and cover large parts of the map.

Todos:
- Conceptualize alternative visualizations
- Create sketches / mockups
- Discuss in group
- Implement

**Comment by felixerdy** [comment]
Some initial concepts

### Polyline
A polyline where the recorded points are connected in chronological order
|Current View|Thinner Lines|Light Basemap|
|---|---|---|
|![Bildschirmfoto 2021-05-19 um 13 52 49](https://user-images.githubusercontent.com/12086004/118987908-01613680-b981-11eb-8ca3-f36c05432d9c.png)|![Bildschirmfoto 2021-05-19 um 13 53 16](https://user-images.githubusercontent.com/12086004/118988006-1342d980-b981-11eb-992a-a04a8cf22c80.png)|![Bildschirmfoto 2021-05-19 um 14 08 22](https://user-images.githubusercontent.com/12086004/118988121-340b2f00-b981-11eb-9c85-4df6071f9277.png)

### Points
Only the recorded points without indication of chronological order. **Rendering a lot of points (e.g. Example Nepal Trajectory) already has a strong negative impact on performance and makes map unusable / causes app crash.**
|Points|Points with Dark Basemap|
|---|---|
|![Bildschirmfoto 2021-05-19 um 14 27 38](https://user-images.githubusercontent.com/12086004/118988348-661c9100-b981-11eb-8e82-ed19e8616188.png)|![Bildschirmfoto 2021-05-19 um 14 30 47](https://user-images.githubusercontent.com/12086004/118988371-6cab0880-b981-11eb-8041-264bf6c54b67.png)|

### Combination of Polyline and Points
Implementation of zoom based visualisation also possible (e.g. large scale: points, low scale: polyline). Still depending on performance when using points.

### Heatmap
Areas with high opacity indicate many recordings
|Few Points|Many Points|
|---|---|
|![Bildschirmfoto 2021-05-25 um 11 09 33](https://user-images.githubusercontent.com/12086004/119471633-c0cf3780-bd49-11eb-9b17-bae8af42af1a.png)|![Bildschirmfoto 2021-05-25 um 10 53 00](https://user-images.githubusercontent.com/12086004/119470586-c8daa780-bd48-11eb-8467-d2222c217704.png)|

**Comment by schrooom** [comment]
Nice work, this looks great overall!

#### Map

I really like the clean and minimalistic dark & lights map-styles, as it fits into our (so far) pretty clean UI really nicely and also seems to work with dark- and light-mode of the app. On top of that those clean and colorless styles really shift the focus from the map towards the actual trajectories, as they are colored in contrast to the map. Independent from the actual visualization of the trajectories themselves, I'd go with these map-styles either way!

#### Trajectory visualization

While I really like the points as a very detailed way of showing each and every location: I think the current polyline-visualzation gives a good idea about the chronology of the location history, so it'd be nice to try and retain that. The idea of combining polyline with points is really good, as we have the 'best of both worlds'.

The heatmap gives great insights to the location history, too - especially looking at clusters - but lacks the level of detail of the other visualizations. My suggestion would be an optional button/switch (possibly integrated to the FAB) to be able to switch back and forth between the heatmap view and 'conventional' view.

##### Points performance

When combining polyline and points, while only showing points at lower scales: Does this impact performance as bad like using points everytime? Otherwise it would be a good way of introducing points, without negatively impacting performance too much.

Either way: The nepal trajectory has something around ~250k locations and is realistically not usable in any scenario (e.g. inference-algorithm is disabled for such data-sizes too). Maybe we should remove it, since it is not really benefitial at the moment. Alternatively we can maybe crop it a smaller size in a way that it is actually usable as a example trajectory.

 Just a thought: Could our map-component (leaflet) be the reason, that large data is not handled well (especially points))? If it is not too much work, we could give alternatives (like mapbox as discussed a few months back) a shot.

**Comment by zven** [comment]
To sum things up: Maybe we give thinner lines combined with less cluttered background map a shot? In addition, I think it would also make sense to remove the Nepal trajectory from the UI for now.

It could also make sense to chose a more performant implementation for the map ui at some point. Although I'd suggest to keep that one for later.

**Comment by noerw** [comment]
### Map
- I also like the theme adaption and clean impression of the lighter maps, but in the past I noticed that these maps omit quite a lot of (sometimes important) details such as footpaths. So we should carefully weight pros & cons for our usecase here
- ratelimits / free quotas should be kept in mind, but for initial studies this shouldn't become an issue with mapbox 

### Visualization
Each viz has a strength for one aspect of data exploration, none can really replace all others.
Having a cronological view is essential for our use case, density seems nice to have.

> My suggestion would be an optional button/switch (possibly integrated to the FAB) to be able to switch back and forth between the heatmap view and 'conventional' view.

:+1: 

### Performance
> When combining polyline and points, while only showing points at lower scales: Does this impact performance as bad like using points everytime? Otherwise it would be a good way of introducing points, without negatively impacting performance too much.

There may be leaflet plugins for selectively creating only objects that are in the viewport ([Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid) might be an option?), but out of the box a combination of lines & points will have the longest time-to-interactive.

To get a snappier experience in general, we could straight go for a webgl based renderer like mapbox-gl or [deck.gl](https://deck.gl/)

> [context: Nepal] Maybe we should remove it

We should certainly keep an example trajectory. I'd just truncate the trajectory to 2-4 weeks & select every Nth (N=20?) sample only as a stopgap?
