### ISSUE TITLE
Inferences: Rethink confidence value

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#77]
The confidence value we compute at the moment is somewhat artificial. 

Instead we could go for an easier system and work with categories (e.g. low, medium and high confidence) to replace the confidence numbers. This makes the confidence-value way more understandable for users in contrast to bare numbers.

- [x] Define confidence-categories using thresholds
- [ ] Potentially: remove/replace the term `confidence`
- [x] Reiterate the UI for the tab `insights`
- [x] Reiterate the UI for inferences in the tab `map` (popup)
- [x] Reiterate the UI for filtering the inferences (top-right button)

**Comment by zven** [comment]
Might be partly covered already here: https://github.com/sitcomlab/simport-learning-app/issues/96

**Comment by jbraese** [comment]
![Screenshot_1641890983](https://user-images.githubusercontent.com/47788955/148910891-2c6f0d8f-5969-4a06-b1f9-c17345723ad6.png)

Here is what the menu looks like now. In the insights tab and map view, the percentages have also been replaced with "High/medium/low confidence". 

The thresholds for high/medium/low confidence are currently 60%, 30% and 0.05% and can be set globally in `src\app\model\inference.ts`. 

I couldn't think of a more suitable word then confidence, so I decided to stick with it for now. 

Any thoughts on the thresholds or suggestions for an alternative term instead of confidence?
