### ISSUE TITLE
Android 11: no location updates

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#97]
Additional: State `running` remains, even if the tracking is not running anymore

**Comment by jbraese** [comment]
On Android 11, after location tracking has been enabled for a while it sometimes shuts off while the "Toggle location tracking" button is still set to "Running". This becomes apparent as no new locations are registered. When toggling the button, the status does not change from "Running" to "Stopped" as expected, but stays on "Running". Clicking it again switches it to "Stopped". 

This issue is usually observed after a period of inactivity of the phone (eg in the morning after sleeping). So far I had no success in reproducing the bug with a short period of inactivity during the day (I tried airplane mode and battery saver mode). I also so far haven't been able to reproduce the bug on an emulated device in Android Studio.

**Comment by jbraese** [comment]
I was able to capture a log of the bug on a Pixel 4a, see attached. After no locations were logged in several hours even though the 
tracking was set to "Running", captured in the log is when I clicked the button three times, resulting in the in-app button being displayed as `Running -click-> Running -click-> Stopped -click-> Running` after which point the tracking was started again as expected. 

[issue97_pixel4a.log](https://github.com/sitcomlab/simport-learning-app/files/7167907/issue97_pixel4a.log)

**Comment by schrooom** [comment]
Quick update:
Unfortunately the logs are not revealing any issues on this problem. I'm currently testing the location-updates on an Android 11 with the changes that I made so far (on branch `feature/android-location-updates`) and probably can report back on the next weekly.

**Comment by zven** [comment]
I'll also test the current state of this branch with some Android devices. I think the issue @jbraese observed was actually twofold: First the tracking stops at a certain point / is stopped (by the OS?). Second, the UI was not updated properly. For now, I would say we can only mitigate the second problem to a certain extent.

**Comment by zven** [comment]
Testing the current state of this branch on Android 7.0 the tracking worked for five days and then stopped. Again, I had to click on the Start/Stop-Button multiple times until I was able to start the location tracking again (button seemed to be stuck in running state).
