### ISSUE TITLE
Reverse geocoding mechanism with privacy friendly requests

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#99]
At the moment, the inferences only contain the coordinates of the inferred work and home locations. It would be much more informative to have an actual address or place name here. In addition, a reverse geocoding mechanism would also be very useful for presenting detected POIs to the user (see here https://github.com/sitcomlab/simport-learning-app/issues/100)

Although we initially had the aim to have _local_ reverse geocoding mechanism to be used for the inferences, for a first version we decided to keep things simple and use external services in a way, that offers at least some privacy protection for the user. This could be realized, for example, with sending a number of dummy locations together with the actual location of specific point to the reverse geocoding service and then pick the right one on client side.

- [ ] develop concept + example script
- [ ] implement functionality / service in actual application
- [ ] use reverse geocoded locations for inferences

**Comment by felixerdy** [comment]
I created a (naive) approach generating random points around the actual point and requesting addresses for all of these points. Check out the stackblitz here: https://stackblitz.com/edit/typescript-dsb6hg

**Comment by jbraese** [comment]
Regarding the privacy-preserving reverse geocoding, linked below is a generalized approach for querying a location based service that uses dummy locations (like Felix's demo above) but deals with the problem of repeated queries exposing the true location over time. Essentially, for a region with frequent queries (eg home location) they generate a fixed set of k corresponding fake regions; whenever a query is sent about a point in the true frequent region, queries are also sent for a dummy location in each of the corresponding fake regions. The information the service is able to acquire over time thus changes from "user likely lives near this location" to "user likely lives in one of these k locations". 

The paper is here https://ieeexplore.ieee.org/abstract/document/8975879 and in Zotero. Note that the paper explores location sharing for whole trajectories and thus needs to worry about further constraints like reachability between points, whereas we could simplify because we only query certain points from our inferences where dummy points cannot be recognized as implausible so easily.

**Comment by schrooom** [comment]
Reverse geocoding is implemented using the Nominatim-Instance from OSM, which comes with various usage-limitations. Therefore:

- requests are done one at a time
- requests are done with delays in between them
- geocoding for inferences is done in two places:
  - during inference-calculation
  - when the user is viewing their inferences
- geocoding results are cached in a database and reused if applicable

Still the geocoding is fairly unstable due to the restrictions of the OSM-Nominatim.
For improving the geocoding in the future, we could use another or even run our own instance of Nominatim.
